// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.17.1
// source: bipb/bi.proto

package hello

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type X struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *X) Reset() {
	*x = X{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bipb_bi_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *X) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*X) ProtoMessage() {}

func (x *X) ProtoReflect() protoreflect.Message {
	mi := &file_bipb_bi_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use X.ProtoReflect.Descriptor instead.
func (*X) Descriptor() ([]byte, []int) {
	return file_bipb_bi_proto_rawDescGZIP(), []int{0}
}

func (x *X) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type Y struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *Y) Reset() {
	*x = Y{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bipb_bi_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Y) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Y) ProtoMessage() {}

func (x *Y) ProtoReflect() protoreflect.Message {
	mi := &file_bipb_bi_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Y.ProtoReflect.Descriptor instead.
func (*Y) Descriptor() ([]byte, []int) {
	return file_bipb_bi_proto_rawDescGZIP(), []int{1}
}

func (x *Y) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_bipb_bi_proto protoreflect.FileDescriptor

var file_bipb_bi_proto_rawDesc = []byte{
	0x0a, 0x0d, 0x62, 0x69, 0x70, 0x62, 0x2f, 0x62, 0x69, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22,
	0x17, 0x0a, 0x01, 0x58, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x1d, 0x0a, 0x01, 0x59, 0x12, 0x18, 0x0a,
	0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07,
	0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x32, 0x1d, 0x0a, 0x06, 0x61, 0x63, 0x74, 0x69, 0x6f,
	0x6e, 0x12, 0x13, 0x0a, 0x03, 0x68, 0x69, 0x74, 0x12, 0x02, 0x2e, 0x58, 0x1a, 0x02, 0x2e, 0x59,
	0x22, 0x00, 0x28, 0x01, 0x30, 0x01, 0x42, 0x13, 0x5a, 0x11, 0x62, 0x69, 0x2e, 0x63, 0x6f, 0x6d,
	0x2f, 0x75, 0x73, 0x65, 0x72, 0x2f, 0x68, 0x65, 0x6c, 0x6c, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_bipb_bi_proto_rawDescOnce sync.Once
	file_bipb_bi_proto_rawDescData = file_bipb_bi_proto_rawDesc
)

func file_bipb_bi_proto_rawDescGZIP() []byte {
	file_bipb_bi_proto_rawDescOnce.Do(func() {
		file_bipb_bi_proto_rawDescData = protoimpl.X.CompressGZIP(file_bipb_bi_proto_rawDescData)
	})
	return file_bipb_bi_proto_rawDescData
}

var file_bipb_bi_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_bipb_bi_proto_goTypes = []interface{}{
	(*X)(nil), // 0: X
	(*Y)(nil), // 1: Y
}
var file_bipb_bi_proto_depIdxs = []int32{
	0, // 0: action.hit:input_type -> X
	1, // 1: action.hit:output_type -> Y
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_bipb_bi_proto_init() }
func file_bipb_bi_proto_init() {
	if File_bipb_bi_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_bipb_bi_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*X); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bipb_bi_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Y); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_bipb_bi_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_bipb_bi_proto_goTypes,
		DependencyIndexes: file_bipb_bi_proto_depIdxs,
		MessageInfos:      file_bipb_bi_proto_msgTypes,
	}.Build()
	File_bipb_bi_proto = out.File
	file_bipb_bi_proto_rawDesc = nil
	file_bipb_bi_proto_goTypes = nil
	file_bipb_bi_proto_depIdxs = nil
}
